version: '2'
volumes:
  data-volume:
  dbmysql-mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: dbmysql-mysql
    volumes:
      - dbmysql-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbmysql
      - MYSQL_DATABASE=dbmysql
      - MYSQL_USER=dbmysql
      - MYSQL_PASSWORD=dbmysql

  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pontos-app
    env_file:
      - .env.docker
    ports:
      - 8090:8080

